language: node_js
node_js:
- '6.3.1'
install:
- npm install
script:
- if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "Building Development package...";
  NODE_ENV=staging webpack; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then echo "Building Production package...";
  NODE_ENV=production webpack -p; fi

deploy:
  - provider: s3
    access_key_id: AKIAJVF4LCEMJR4UUHDQ
    secret_access_key:
        secure: r+wIf+5ZwODe0no6RvGGhWYqAfvwTne3GEZSne5zTOYI4QWc/Nx95GGOw00lGutuFPHgpjtRNkG9CqyhEQmNVRzYClm4jr3srdiU7R4NUjl4zYGroZ03cgQyOswVlstDyi550DQAW1jCeI2f+GmmECsysRmkCGQkPiik2iJ5lPDNitWwEHozUMg42cpDaYY6z3Qpi2cdPhPrfZdk+3mvCLVF11IHM0eFHO2WxyFIP+IIBxtOUJSFKK/NCX4UE6iH4pZ7bSQgAWspmWuSANu8snbI3as3EjB4EwIhFQ+zgDULE2fjA346xZA8PnohSVuW23TkIqWkUoEh5zFMEy9xGHc4a2Y3dccKfK5zUl0KMqS6LljrJM8aqegioXR7suo5Eqgo9SGHovvZ7WUYYaBebyNM5nI3pXQW7QJNwb1HdCBg2AW8kx5JFw6aMx/sfzEcJlsKemAp8g1kYJbc4MX5pCoQJQHyYGaAYmZWSZP7hq+dnJZcULTAVB0v+8yVQ5UdvbeoxOLP4BIG2ZFpIHng4itZCwGjKr6fGFBlWTJPfQwn47rbvt53Vo8538wZa7We0ydVA36GBDQvUeIxOhlQN5HXjIInMs44F/bZQcqhKZR9e6LkOQK17nApoQIfhTu6+aiOsw6bR9zLOFR6Yk83rBcQqGp4/u8AEPJQhiLURV8=
    bucket: dev.senzolive.com
    region: eu-central-1
    local-dir: build
    acl: public_read
    skip_cleanup: true
    on:
      repo: futurice/senzoit-client
      branch: develop

  - provider: s3
    access_key_id: AKIAJVF4LCEMJR4UUHDQ
    secret_access_key:
        secure: r+wIf+5ZwODe0no6RvGGhWYqAfvwTne3GEZSne5zTOYI4QWc/Nx95GGOw00lGutuFPHgpjtRNkG9CqyhEQmNVRzYClm4jr3srdiU7R4NUjl4zYGroZ03cgQyOswVlstDyi550DQAW1jCeI2f+GmmECsysRmkCGQkPiik2iJ5lPDNitWwEHozUMg42cpDaYY6z3Qpi2cdPhPrfZdk+3mvCLVF11IHM0eFHO2WxyFIP+IIBxtOUJSFKK/NCX4UE6iH4pZ7bSQgAWspmWuSANu8snbI3as3EjB4EwIhFQ+zgDULE2fjA346xZA8PnohSVuW23TkIqWkUoEh5zFMEy9xGHc4a2Y3dccKfK5zUl0KMqS6LljrJM8aqegioXR7suo5Eqgo9SGHovvZ7WUYYaBebyNM5nI3pXQW7QJNwb1HdCBg2AW8kx5JFw6aMx/sfzEcJlsKemAp8g1kYJbc4MX5pCoQJQHyYGaAYmZWSZP7hq+dnJZcULTAVB0v+8yVQ5UdvbeoxOLP4BIG2ZFpIHng4itZCwGjKr6fGFBlWTJPfQwn47rbvt53Vo8538wZa7We0ydVA36GBDQvUeIxOhlQN5HXjIInMs44F/bZQcqhKZR9e6LkOQK17nApoQIfhTu6+aiOsw6bR9zLOFR6Yk83rBcQqGp4/u8AEPJQhiLURV8=
    bucket: www.senzolive.com
    region: eu-central-1
    local-dir: build
    acl: public_read
    skip_cleanup: true
    on:
      repo: futurice/senzoit-client
      branch: master

notifications:
  flowdock: 1e14c54ff2599d0757c48050c14525fe
