language: node_js
node_js:
- '6.3.1'
install:
- npm install
script:
- if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "Building Development package...";
  NODE_ENV=staging webpack; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then echo "Building Production package...";
  NODE_ENV=production webpack -p; fi